version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: echo "everything is a success"
      - deploy:
        name: digital-ocean
        command:
        - echo 'deploying master branch'
        - ssh -v $DROPLET_USER@$DROPLET_IP "cd /var/www/cinemaholics/; echo 'hi from circleci' >> hi.txt" 
