version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - run: echo "everything is a success"
  deployment:
    master:
      branch: master
      commands:
        - echo 'deploying master branch'
        - ssh -v $DROPLET_USER@$DROPLET_IP "cd /var/www/cinemaholics/; echo 'hi from circleci' >> hi.txt" 
